import styles from "../../styles/Home.module.css";
import Head from "next/head";

export default function Instalaciones() {
  return(
    <div>
      <Head>
        <title>Villa Ladridos 🐾</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1>Instalaciones</h1>
      </main>

    </div>
  )
}
