import {useState} from 'react';
import Head from 'next/head';
import DatePicker from 'react-datepicker';
import {registerLocale, setDefaultLocale} from "react-datepicker";
import es from 'date-fns/locale/es';

import styles from '../../styles/Home.module.css';
import stylesReservas from '../../styles/Reservas.module.css';
import 'react-datepicker/dist/react-datepicker.css';

import {FaAngleDown, FaAngleUp} from "react-icons/fa";

export default function Reservas() {

  // excludeDates={}
  registerLocale('es', es)

  const [startDateGD, setStartDateGD] = useState(new Date());

  const [startDateRC, setStartDateRC] = useState(new Date());
  const [endDateRC, setEndDateRC] = useState(null);
  const onChange = (dates) => {
    const [start, end] = dates;
    setStartDateRC(start);
    setEndDateRC(end);
  };

  const [showGD, setShowGD] = useState(false);
  const [showRC, setShowRC] = useState(false);

  return (
    <div className={stylesReservas.bg}>
      <Head>
        <title>Villa Ladridos 🐾</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1 className={stylesReservas.title}>RESERVAS</h1>
        <div
          className={stylesReservas.accordion__guarderia}
        >
          <div
            className={stylesReservas.accordion__header}
            onClick={() => {
              setShowGD(!showGD);
              setShowRC(false);
            }}
          >
            <h2>Guardería de día</h2>{showGD ? <FaAngleUp/> : <FaAngleDown/>}
          </div>
          {
            showGD
              ?
              <div className={stylesReservas.form}>
                <DatePicker
                  selected={startDateGD}
                  onChange={(date) => setStartDateGD(date)}
                  startDate={startDateGD}
                  locale="es"
                  calendarStartDay={1}
                  inline
                />
                <form>
                  <input type="text" placeholder="Nombre"/>
                  <input type="email" placeholder="Email"/>
                  <input type="phone" placeholder="Teléfono"/>
                  <label htmlFor="num">Número de peludos</label>
                  <input type="number" id="num" min={1}/>
                  <button type="submit" className={stylesReservas.button}>Reservar</button>
                </form>
              </div>
              : ""
          }
        </div>
        <div
          className={stylesReservas.accordion__residencia}
          onClick={() => {
            setShowRC(!showRC);
            setShowGD(false);
          }}
        >
          <div className={stylesReservas.accordion__header}>
            <h2>Residencia canina</h2>{showRC ? <FaAngleUp/> : <FaAngleDown/>}
          </div>
          {
            showRC
              ?
              <div  className={stylesReservas.form}>
                <DatePicker
                  selected={startDateRC}
                  onChange={onChange}
                  startDate={startDateRC}
                  endDate={endDateRC}
                  locale="es"
                  calendarStartDay={1}
                  selectsRange
                  selectsDisabledDaysInRange
                  inline
                />
                <form>
                  <input type="text" placeholder="Nombre"/>
                  <input type="email" placeholder="Email"/>
                  <input type="phone" placeholder="Teléfono"/>
                  <label htmlFor="num">Número de peludos</label>
                  <input type="number" id="num" min={1}/>
                  <button type="submit" className={stylesReservas.button}>Reservar</button>
                </form>
              </div>

              : ""
          }

        </div>
      </main>

    </div>
  )
}
