import Head from "next/head";
import styles from "../../styles/Home.module.css";
import stylesContacto from "../../styles/Contacto.module.css"
import stylesReservas from "../../styles/Reservas.module.css";

export default function Contacto() {
  return (
    <div>
      <Head>
        <title>Villa Ladridos 🐾</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={stylesContacto.main}>
        <div className={stylesContacto.form}>
          <form>
            <h1>Contáctanos</h1>
            <input type="text" placeholder="Nombre"/>
            <input type="email" placeholder="Email"/>
            <input type="phone" placeholder="Teléfono"/>
            <textarea placeholder="Mensaje" rows={80}/>
            <button type="submit" className={stylesReservas.button}>Enviar</button>
          </form>
        </div>
        <div className={stylesContacto.asideImage}>&nbsp;</div>
      </main>

    </div>
  )
}
