import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function Contacto() {
  return (
    <div>
      <Head>
        <title>Villa Ladridos 🐾</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1>Contáctanos</h1>
      </main>

    </div>
  )
}
