import Head from 'next/head';
import containerStyle from '../../styles/Container.module.css'
import contactoStyle from '../../styles/Contacto.module.css'
import reservaStyle from '../../styles/Reservas.module.css';

export default function Contacto() {
  return (
    <div>
      <Head>
        <title>Villa Ladridos 🐾</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={contactoStyle.main}>
        <div className={contactoStyle.form}>
          <form className={containerStyle.container}>
            <h1>Contáctanos</h1>
            <input type="text" placeholder="Nombre"/>
            <input type="email" placeholder="Email"/>
            <input type="phone" placeholder="Teléfono"/>
            <textarea placeholder="Mensaje" rows={80}/>
            <button type="submit" className={reservaStyle.button}>Enviar</button>
          </form>
        </div>
        <div className={contactoStyle.asideImage}>&nbsp;</div>
      </main>
    </div>
  )
}
