import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Villa Ladridos 🐾</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div className={styles.landing}>
        <h1>Tu peludito en las mejores manos</h1>
      </div>

      <main className={styles.main}>
        <h1>Villa Ladridos, hotel canino</h1>
        <h3>¿Tienes que viajar y no sabes con quién dejar a tu mejor amigo? ¿Tu peludito se queda en casa solo todo el
          día porque estás trabajando?</h3>
        <h3>¡Nosotras sabemos cómo ayudarte!</h3>
        <div className={styles.main__presentation}>
          <div>
            <p>
              En Villa Ladridos contamos con un amplio jardín donde
              pueden correr y jugar y además, <strong>no existen jaulas</strong>. Queremos que tu mascota se sienta como
              en
              casa, por lo que
              tendrán acceso libre por todas nuestras instalaciones, estando en su habitación únicamente para comer y
              dormir.
              Como nuestra mayor preocupación es el bienestar de nuestros clientes de 4 patas y sus dueños, ofrecemos
              <strong> servicios webcam</strong> para que echarlo de menos no se haga tan difícil. Podrás acceder a
              todas
              nuestras cámaras web
              desde cualquier lugar y en cualquier momento.
            </p>
            <p>
              Villa Ladridos nace ante la necesidad que nos surge para encontrar un buen alojamiento donde dejar a
              nuestras mascotas, una guardería con todas las comodidades y seguridades para que se sientan como en casa
              y disfruten de su estancia. Es muy importante para nosotros que tu perro este a gusto en nuestra
              guardería, así como que tú te sientas cómodo y seguro dejándonos a tu mejor amigo. Es por ello que tenemos
              a disposición las cámaras web para tu mayor tranquilidad.
            </p>
          </div>
          <div className={styles.main__presentation__image}>
            &nbsp;
          </div>
        </div>


      </main>
    </div>
  )
}
