import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Villa Ladridos 🐾</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1>Home</h1>
        <p>
          Nuestra empresa consiste en un hotel para mascotas, aquí recibirán una serie de servicios y
          cuidados de los que hablaremos a continuación. Además, contaremos con una ventaja
          comparativa adicional y es que, a diferencia del resto de guarderías caninas presentes en la isla,
          contaremos con un servicio de webcams online.
        </p>
        <p>
          El cliente entrará en nuestra aplicación móvil/web, previa invitación nuestra para acceder a la
          cuenta de la empresa en la aplicación.
        </p>
        <p>
          Dichas cámaras estarán repartidas por todas las zonas comunes del recinto y de manera
          individual en cada una de las habitaciones. De este modo, el cliente tendrá un seguimiento de
          su mascota las 24 horas del día desde cualquier parte en la que se encuentre.
        </p>
        <p>
          Estas cámaras ya vienen con la aplicación incluida de forma gratuita, por lo que no nos supondrá
          un coste adicional. Solo tendremos que hacer la instalación en nuestros dispositivos, y cuando
          el cliente venga a dejar a su perro en nuestra residencia, le daremos permiso como invitado,
          para que pueda acceder a nuestra aplicación hasta
        </p>
      </main>
    </div>
  )
}
